In [10]:
import pandas as pd
import yaml
import pandas as pd
import numpy as np
from scipy import stats

In [11]:
with open("../config.yaml", "r") as file:
    paths = yaml.safe_load(file)

print(paths['data']['clean']['file1'])
print(paths['data']['clean']['file2'])
print(paths['data']['clean']['file3'])
print(paths['data']['clean']['file4'])
print(paths['data']['clean']['file5'])
print(paths['data']['clean']['file6'])
print(paths['data']['clean']['file7'])

../data/clean/earthquake_data_clean.csv
../data/clean/inventory_clean_redundant.csv
../data/clean/value_1997-2020_clean.csv
../data/clean/value_2019-2024_clean.csv
../data/clean/values_joined_clean.csv
../data/clean/values_pivotedback.csv
../data/clean/combined_df_value+inventory.csv

In [12]:
# load files

df1 = pd.read_csv(paths['data']['clean']['file7']) #, usecols=[0, 1, 2, 3, 4])
df2 = pd.read_csv(paths['data']['clean']['file2'])
df3 = pd.read_csv(paths['data']['clean']['file3'])
df4 = pd.read_csv(paths['data']['clean']['file4'])

Hypothesis testing value affected city vs benchmark

In [13]:
# preliminary view

df1.head()

,index,region,year,value,total,total_occupied,total_not_occupied,oppucation_ratio
0,0,'s-Gravenhage (gemeente),2012,207.0,241376.0,219180.0,22196.0,0.908044
1,1,'s-Gravenhage (gemeente),2013,199.0,244880.0,222196.0,22684.0,0.907367
2,2,'s-Gravenhage (gemeente),2014,188.0,249994.0,225202.0,24792.0,0.900830
3,3,'s-Gravenhage (gemeente),2015,184.0,251374.0,227464.0,23910.0,0.904883
4,4,'s-Gravenhage (gemeente),2016,188.0,253210.0,230398.0,22812.0,0.909909

In [14]:
df1['region'].unique()

array(["'s-Gravenhage (gemeente)", "'s-Hertogenbosch", 'Aa en Hunze',
       'Aalburg', 'Aalsmeer', 'Aalten', 'Achtkarspelen', 'Alblasserdam',
       'Albrandswaard', 'Alkmaar', 'Almelo', 'Almere',
       'Alphen aan den Rijn', 'Alphen-Chaam', 'Altena', 'Ameland',
       'Amersfoort', 'Amstelveen', 'Amsterdam', 'Apeldoorn', 'Appingedam',
       'Arnhem', 'Assen', 'Asten', 'Baarle-Nassau', 'Baarn',
       'Barendrecht', 'Barneveld', 'Bedum', 'Beek (L.)', 'Beekdaelen',
       'Beemster', 'Beesel', 'Bellingwedde', 'Berg en Dal', 'Bergambacht',
       'Bergeijk', 'Bergen (L.)', 'Bergen (NH.)', 'Bergen op Zoom',
       'Berkelland', 'Bernheze', 'Bernisse', 'Best', 'Beuningen',
       'Beverwijk', 'Binnenmaas', 'Bladel', 'Blaricum', 'Bloemendaal',
       'Boarnsterhim', 'Bodegraven-Reeuwijk', 'Boekel', 'Borger-Odoorn',
       'Borne', 'Borsele', 'Boskoop', 'Boxmeer', 'Boxtel', 'Breda',
       'Brielle', 'Bronckhorst', 'Brummen', 'Brunssum', 'Bunnik',
       'Bunschoten', 'Buren', 'Bussum', 'Capelle aan den IJssel',
       'Castricum', 'Coevorden', 'Cranendonck', 'Cromstrijen', 'Cuijk',
       'Culemborg', 'Dalfsen', 'Dantumadiel', 'De Bilt',
       'De Friese Meren', 'De Fryske Marren', 'De Marne',
       'De Ronde Venen', 'De Wolden', 'Delft', 'Delfzijl', 'Den Helder',
       'Deurne', 'Deventer', 'Diemen', 'Dinkelland', 'Dirksland',
       'Doesburg', 'Doetinchem', 'Dongen', 'Dongeradeel', 'Dordrecht',
       'Drechterland', 'Drenthe (PV)', 'Drimmelen', 'Dronten', 'Druten',
       'Duiven', 'Echt-Susteren', 'Edam-Volendam', 'Ede', 'Eemnes',
       'Eemsmond', 'Eersel', 'Eijsden-Margraten', 'Eindhoven', 'Elburg',
       'Emmen', 'Enkhuizen', 'Enschede', 'Epe', 'Ermelo', 'Etten-Leur',
       'Ferwerderadiel', 'Flevoland (PV)', 'Franekeradeel',
       'Friesland (PV)', 'Gaasterl√¢n-Sleat', 'Geertruidenberg',
       'Gelderland (PV)', 'Geldermalsen', 'Geldrop-Mierlo',
       'Gemert-Bakel', 'Gennep', 'Giessenlanden', 'Gilze en Rijen',
       'Goedereede', 'Goeree-Overflakkee', 'Goes', 'Goirle',
       'Gooise Meren', 'Gorinchem', 'Gouda', 'Graafstroom',
       'Graft-De Rijp', 'Grave', 'Groesbeek', 'Groningen (PV)',
       'Groningen (gemeente)', 'Grootegast', 'Gulpen-Wittem',
       'Haaksbergen', 'Haaren', 'Haarlem',
       'Haarlemmerliede en Spaarnwoude', 'Haarlemmermeer', 'Halderberge',
       'Hardenberg', 'Harderwijk', 'Hardinxveld-Giessendam', 'Haren',
       'Harenkarspel', 'Harlingen', 'Hattem', 'Heemskerk', 'Heemstede',
       'Heerde', 'Heerenveen', 'Heerhugowaard', 'Heerlen', 'Heeze-Leende',
       'Heiloo', 'Hellendoorn', 'Hellevoetsluis', 'Helmond',
       'Hendrik-Ido-Ambacht', 'Hengelo (O.)', 'Het Hogeland', 'Heumen',
       'Heusden', 'Hillegom', 'Hilvarenbeek', 'Hilversum',
       'Hoeksche Waard', 'Hof van Twente', 'Hollands Kroon', 'Hoogeveen',
       'Hoogezand-Sappemeer', 'Hoorn', 'Horst aan de Maas', 'Houten',
       'Huizen', 'Hulst', 'IJsselstein', 'Kaag en Braassem', 'Kampen',
       'Kapelle', 'Katwijk', 'Kerkrade', 'Koggenland',
       'Kollumerland en Nieuwkruisland', 'Korendijk',
       'Krimpen aan den IJssel', 'Krimpenerwaard', 'Laarbeek', 'Landerd',
       'Landgraaf', 'Landsmeer', 'Langedijk', 'Lansingerland',
       'Laren (NH.)', 'Leek', 'Leerdam', 'Leeuwarden', 'Leeuwarderadeel',
       'Leiden', 'Leiderdorp', 'Leidschendam-Voorburg', 'Lelystad',
       'Lemsterland', 'Leudal', 'Leusden', 'Liesveld', 'Limburg (PV)',
       'Lingewaal', 'Lingewaard', 'Lisse', 'Littenseradiel', 'Lochem',
       'Loon op Zand', 'Lopik', 'Loppersum', 'Losser', 'Maasdonk',
       'Maasdriel', 'Maasgouw', 'Maassluis', 'Maastricht', 'Marum',
       'Medemblik', 'Meerssen', 'Meierijstad', 'Menameradiel',
       'Menterwolde', 'Meppel', 'Middelburg (Z.)', 'Middelharnis',
       'Midden-Delfland', 'Midden-Drenthe', 'Midden-Groningen',
       'Mill en Sint Hubert', 'Millingen aan de Rijn', 'Moerdijk',
       'Molenlanden', 'Molenwaard', 'Montferland', 'Montfoort',
       'Mook en Middelaar', 'Muiden', 'Naarden', 'Neder-Betuwe',
       'Nederland', 'Nederlek', 'Nederweert', 'Neerijnen',
       'Nieuw-Lekkerland', 'Nieuwegein', 'Nieuwkoop', 'Nijkerk',
       'Nijmegen', 'Nissewaard', 'Noord-Beveland', 'Noord-Brabant (PV)',
       'Noord-Holland (PV)', 'Noordenveld', 'Noordoostpolder',
       'Noordwijk', 'Noordwijkerhout', 'Nunspeet', 'Nuth', 'Oegstgeest',
       'Oirschot', 'Oisterwijk', 'Oldambt', 'Oldebroek', 'Oldenzaal',
       'Olst-Wijhe', 'Ommen', 'Onderbanken', 'Oost Gelre', 'Oosterhout',
       'Oostflakkee', 'Ooststellingwerf', 'Oostzaan', 'Opmeer',
       'Opsterland', 'Oss', 'Oud-Beijerland', 'Oude IJsselstreek',
       'Ouder-Amstel', 'Ouderkerk', 'Oudewater', 'Overbetuwe',
       'Overijssel (PV)', 'Papendrecht', 'Peel en Maas', 'Pekela',
       'Pijnacker-Nootdorp', 'Purmerend', 'Putten', 'Raalte',
       'Reimerswaal', 'Renkum', 'Renswoude', 'Reusel-De Mierden',
       'Rheden', 'Rhenen', 'Ridderkerk', 'Rijnwaarden', 'Rijnwoude',
       'Rijssen-Holten', 'Rijswijk (ZH.)', 'Roerdalen', 'Roermond',
       'Roosendaal', 'Rotterdam', 'Rozendaal', 'Rucphen', 'Schagen',
       'Schermer', 'Scherpenzeel', 'Schiedam', 'Schiermonnikoog',
       'Schijndel', 'Schinnen', 'Schoonhoven', 'Schouwen-Duiveland',
       'Simpelveld', 'Sint Anthonis', 'Sint-Michielsgestel',
       'Sint-Oedenrode', 'Sittard-Geleen', 'Skarsterl√¢n', 'Sliedrecht',
       'Slochteren', 'Sluis', 'Smallingerland', 'Soest', 'Someren',
       'Son en Breugel', 'Spijkenisse', 'Stadskanaal', 'Staphorst',
       'Stede Broec', 'Steenbergen', 'Steenwijkerland', 'Stein (L.)',
       'Stichtse Vecht', 'Strijen', 'Ten Boer', 'Terneuzen',
       'Terschelling', 'Texel', 'Teylingen', 'Tholen', 'Tiel', 'Tilburg',
       'Tubbergen', 'Twenterand', 'Tynaarlo', 'Tytsjerksteradiel',
       'Ubbergen', 'Uden', 'Uitgeest', 'Uithoorn', 'Urk', 'Utrecht (PV)',
       'Utrecht (gemeente)', 'Utrechtse Heuvelrug', 'Vaals',
       'Valkenburg aan de Geul', 'Valkenswaard', 'Veendam', 'Veenendaal',
       'Veere', 'Veghel', 'Veldhoven', 'Velsen', 'Venlo', 'Venray',
       'Vianen', 'Vijfheerenlanden', 'Vlaardingen', 'Vlagtwedde',
       'Vlieland', 'Vlissingen', 'Vlist', 'Voerendaal', 'Voorschoten',
       'Voorst', 'Vught', 'Waadhoeke', 'Waalre', 'Waalwijk',
       'Waddinxveen', 'Wageningen', 'Wassenaar', 'Waterland', 'Weert',
       'Weesp', 'Werkendam', 'West Betuwe', 'West Maas en Waal',
       'Westerkwartier', 'Westerveld', 'Westervoort', 'Westerwolde',
       'Westland', 'Weststellingwerf', 'Westvoorne', 'Wierden', 'Wijchen',
       'Wijdemeren', 'Wijk bij Duurstede', 'Winsum', 'Winterswijk',
       'Woensdrecht', 'Woerden', 'Wormerland', 'Woudenberg', 'Woudrichem',
       'Zaanstad', 'Zaltbommel', 'Zandvoort', 'Zederik', 'Zeeland (PV)',
       'Zeevang', 'Zeewolde', 'Zeist', 'Zevenaar', 'Zijpe', 'Zoetermeer',
       'Zoeterwoude', 'Zuid-Holland (PV)', 'Zuidhorn', 'Zuidplas',
       'Zundert', 'Zutphen', 'Zwartewaterland', 'Zwijndrecht', 'Zwolle',
       'het Bildt'], dtype=object)

In [15]:
search_string = 'PV'
matching_rows = df1[df1['region'].str.contains(search_string, case=False, na=False)]

matching_rows['region'].unique()

array(['Drenthe (PV)', 'Flevoland (PV)', 'Friesland (PV)',
       'Gelderland (PV)', 'Groningen (PV)', 'Limburg (PV)',
       'Noord-Brabant (PV)', 'Noord-Holland (PV)', 'Overijssel (PV)',
       'Utrecht (PV)', 'Zeeland (PV)', 'Zuid-Holland (PV)'], dtype=object)

In [16]:
df_targetcity = df1[df1['region']=='Appingedam']
df_targetcity

,index,region,year,value,total,total_occupied,total_not_occupied,oppucation_ratio
240,240,Appingedam,2012,154.0,5732.0,5427.0,305.0,0.946790
241,241,Appingedam,2013,149.0,5785.0,5429.0,356.0,0.938462
242,242,Appingedam,2014,142.0,5840.0,5518.0,322.0,0.944863
243,243,Appingedam,2015,134.0,5850.0,5574.0,276.0,0.952821
244,244,Appingedam,2016,131.0,5881.0,5622.0,259.0,0.955960
245,245,Appingedam,2017,133.0,5899.0,5647.0,252.0,0.957281
246,246,Appingedam,2018,138.0,5925.0,5638.0,287.0,0.951561
247,247,Appingedam,2019,143.0,6032.0,5621.0,411.0,0.931863
248,248,Appingedam,2020,155.0,6042.0,5639.0,403.0,0.933300
249,249,Appingedam,2021,NaN,NaN,NaN,NaN,NaN
250,250,Appingedam,2022,NaN,NaN,NaN,NaN,NaN
251,251,Appingedam,2023,NaN,NaN,NaN,NaN,NaN

In [44]:
# output2 = df1[(df1['region'] == 'Leeuwarden') | (df1['region'] == 'Appingedam')]
# output2 = output2.dropna()
# output2.to_csv('output2.csv', index=False)

In [24]:
df_target_city = df1[df1['region'] == 'Appingedam']
df_benchmark_city = df1[df1['region'] == 'Leeuwarden']
df_target_region = df1[df1['region'] == 'Groningen (PV)']
df_benchmark_region = df1[df1['region'] == 'Friesland (PV)']

# drop NaNs
df_target_city = df_target_city.dropna()
df_benchmark_city = df_benchmark_city.dropna()
df_target_region = df_target_region.dropna()
df_benchmark_region = df_benchmark_region.dropna()

In [55]:
# Weighted two-sample T-test - Target city vs Benchmark city

# Extract values and weights for both regions
values_target = df_target_city['value']
weights_target = df_target_city['total']

values_benchmark = df_benchmark_city['value']
weights_benchmark = df_benchmark_city['total']

# Function to compute the weighted mean
def weighted_mean(values, weights):
    return np.sum(values * weights) / np.sum(weights)

# Function to compute the weighted variance
def weighted_variance(values, weights):
    mean = weighted_mean(values, weights)
    variance = np.sum(weights * (values - mean) ** 2) / np.sum(weights)
    return variance

# Calculate the weighted means
mean_target = weighted_mean(values_target, weights_target)
mean_benchmark = weighted_mean(values_benchmark, weights_benchmark)

# Calculate the weighted variances
var_target = weighted_variance(values_target, weights_target)
var_benchmark = weighted_variance(values_benchmark, weights_benchmark)

# Calculate the number of samples (n)
n_target = len(values_target)
n_benchmark = len(values_benchmark)

# Calculate the t-statistic
t_statistic = (mean_target - mean_benchmark) / np.sqrt((var_target / n_target) + (var_benchmark / n_benchmark))

# Degrees of freedom for weighted t-test (approximation using Welch-Satterthwaite equation)
df_numerator = ((var_target / n_target) + (var_benchmark / n_benchmark)) ** 2
df_denominator = ((var_target / n_target) ** 2 / (n_target - 1)) + ((var_benchmark / n_benchmark) ** 2 / (n_benchmark - 1))
degrees_of_freedom = df_numerator / df_denominator

# Calculate the p-value for a one-sided t-test (to test if target is lower than benchmark)
p_value = stats.t.cdf(t_statistic, df=degrees_of_freedom)

# Output the results
print(f"t-statistic: {t_statistic}")
print(f"p-value: {p_value}")

alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: target city has a lower value than benchmark city.")
else:
    print("Fail to reject the null hypothesis: No evidence that target city has a lower value than benchmark city.")

t-statistic: -2.036101931888404
p-value: 0.03172750581528492
Reject the null hypothesis: target city has a lower value than benchmark city.

Weighted two-sample T-test - Target region vs Benchmark region

In [56]:
# Weighted two-sample T-test - Target region vs Benchmark region

# Extract values and weights for both regions
values_target = df_target_region['value']
weights_target = df_target_region['total']

values_benchmark = df_benchmark_region['value']
weights_benchmark = df_benchmark_region['total']

# Function to compute the weighted mean
def weighted_mean(values, weights):
    return np.sum(values * weights) / np.sum(weights)

# Function to compute the weighted variance
def weighted_variance(values, weights):
    mean = weighted_mean(values, weights)
    variance = np.sum(weights * (values - mean) ** 2) / np.sum(weights)
    return variance

# Calculate the weighted means
mean_target = weighted_mean(values_target, weights_target)
mean_benchmark = weighted_mean(values_benchmark, weights_benchmark)

# Calculate the weighted variances
var_target = weighted_variance(values_target, weights_target)
var_benchmark = weighted_variance(values_benchmark, weights_benchmark)

# Calculate the number of samples (n)
n_target = len(values_target)
n_benchmark = len(values_benchmark)

# Calculate the t-statistic
t_statistic = (mean_target - mean_benchmark) / np.sqrt((var_target / n_target) + (var_benchmark / n_benchmark))

# Degrees of freedom for weighted t-test (approximation using Welch-Satterthwaite equation)
df_numerator = ((var_target / n_target) + (var_benchmark / n_benchmark)) ** 2
df_denominator = ((var_target / n_target) ** 2 / (n_target - 1)) + ((var_benchmark / n_benchmark) ** 2 / (n_benchmark - 1))
degrees_of_freedom = df_numerator / df_denominator

# Calculate the p-value for a one-sided t-test (to test if target is lower than benchmark)
p_value = stats.t.cdf(t_statistic, df=degrees_of_freedom)

# Output the results
print(f"t-statistic: {t_statistic}")
print(f"p-value: {p_value}")

alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: target region has a lower value than benchmark region.")
else:
    print("Fail to reject the null hypothesis: No evidence that target region has a lower value than benchmark region.")

t-statistic: 4.47110648224146
p-value: 0.9998533323352661
Fail to reject the null hypothesis: No evidence that target region has a lower value than benchmark region.

In [49]:

# Filter data for "Target city" and "Benchmark"
df_target_city = df1[df1['region'] == 'Appingedam']
df_benchmark_city = df1[df1['region'] == 'Leeuwarden']

# Extract the occupation_ratio for both regions
occupation_targetcity = df_target_city['oppucation_ratio'].dropna()
occupation_benchmarkcity = df_benchmark_city['oppucation_ratio'].dropna()

# Perform Welch's t-test for unequal variances
t_statistic, p_value = stats.ttest_ind(occupation_targetcity, occupation_benchmarkcity, equal_var=False, alternative='less')

# Output the results
print(f"t-statistic: {t_statistic}")
print(f"p-value: {p_value}")

# Check if we can reject the null hypothesis at a significance level of 0.05
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: target city has a lower occupation ratio than benchmark city.")
else:
    print("Fail to reject the null hypothesis: No evidence that target city has a lower occupation ratio than benchmark city.")

t-statistic: -2.0423284427680066
p-value: 0.032634033234673857
Reject the null hypothesis: target city has a lower occupation ratio than benchmark city.

In [50]:

# Filter data for "Target region" and "Benchmark"
df_target_region = df1[df1['region'] == 'Groningen (PV)']
df_benchmark_region = df1[df1['region'] == 'Friesland (PV)']

# Extract the occupation_ratio for both regions
occupation_targetregion = df_target_region['oppucation_ratio'].dropna()
occupation_benchmarkregion = df_benchmark_region['oppucation_ratio'].dropna()

# Perform Welch's t-test for unequal variances
t_statistic, p_value = stats.ttest_ind(occupation_targetregion, occupation_benchmarkregion, equal_var=False, alternative='less')

# Output the results
print(f"t-statistic: {t_statistic}")
print(f"p-value: {p_value}")

# Check if we can reject the null hypothesis at a significance level of 0.05
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: target region has a lower occupation ratio than benchmark region.")
else:
    print("Fail to reject the null hypothesis: No evidence that target region has a lower occupation ratio than benchmark region.")

t-statistic: 0.7717476188368193
p-value: 0.7752360050671931
Fail to reject the null hypothesis: No evidence that target region has a lower occupation ratio than benchmark region.